// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Url struct {
	ID          int64
	Url         string
	ShortCode   string
	AccessCount int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
